const sidebars = {
  Siderbar_Introduction: [
    {
      type: 'doc',
      id: 'Home/指南'
    },
  ],
  Sidebar_CompurterBasic: [
    'ComputerBasic/导航',
    {
      type: 'category',
      label: '初探',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ComputerBasic/初探'
        },
      ]
    },
  ],
  Sidebar_Java: [
    'Java/导航',
    {
      type: 'category',
      label: '初探',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Java/初探'
        },
      ]
    },
    {
      type: 'category',
      label: '再探',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Java/再探'
        },
      ]
    },
  ],
  Sidebar_Database: [
    'Database/导航',
  ],
  Sidebar_Rust: [
    'Rust/导航',
  ]
};

module.exports = sidebars;
