const sidebars = {
  Siderbar_Introduction: [
    {
      type: 'doc',
      id: 'Home/指南'
    },
    {
      type: 'doc',
      id: 'Home/关于作者'
    },
    {
      type: 'doc',
      id: 'Home/使用 Github Pages 搭建个人知识库',
    },
    {
      type: 'doc',
      id: 'Home/在 Win11 上获得 Linux 的终端体验',
    }
  ],
  Sidebar_CompurterBasic: [
    'ComputerBasic/导航',
    {
      type: 'category',
      label: '初探',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'ComputerBasic/初探'
        },
      ]
    },
  ],
  Sidebar_Java: [
    'Java/导航',
    {
      type: 'category',
      label: '初探',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Java/初探'
        },
      ]
    },
    {
      type: 'category',
      label: '再探',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Java/再探'
        },
      ]
    },
  ],
  Sidebar_Database: [
    'Database/导航',
  ],
};

module.exports = sidebars;
